### PR TITLE
feat: allow export as RawFrame

### LINKED ISSUE #18: Proposal: make Exporter dynamic
First, thanks for creating this package ;)

I wanted to propose a change to the API for Exporter. The current API is really coupled to export a GIF(or any composition resulting in List<int>). In my use case for example I will not need a List<int> since my plan is to send to a backend the frames captured by the recorded. So something like this will be sufficient for me:

````dart
class FramesExporter implements Exporter {
  final List<Frame> _frames = [];
  @override
  void onNewFrame(Frame frame) {
    _frames.add(frame);
  }

  @override
  Future<List<ByteData>> export() async {
    final images = <ByteData>[];
    for (final frame in _frames) {
      final bytes =
          await frame.image.toByteData(format: ui.ImageByteFormat.png);
      if (bytes != null) {
        images.add(bytes);
      } else {
        print('Skipped frame while enconding');
      }
    }
    return images;
  }
}
````

This can be achieved by changing the Exporter class to:

```dart
abstract class Exporter {
  void onNewFrame(Frame frame);
  Future export();
}
```

And that way your current GifExporter is not affected and there is not any breaking change. Let me know if you are ok with this and I can create a PR since I already have a branch with the changes also adding a new example where instead of exporting a GIF simply display in a ListView the frames captured.

Thanks!

### PR DESCRIPTION
**Pull request by omartinma**
Closes #18

### CODE REVIEW

**Comment by omartinma** [comment]
Another approach to avoid the dependency between Exporter and ScreenRecorderController might be move the logic of onNewFrame to the controller. Then the user whenever wants to export will simply create a Exporter with the frames as parameter in the constructor. This way will simplify testing in the future as well. @ueman

**Comment by ueman** [comment]
> Another approach to avoid the dependency between Exporter and ScreenRecorderController might be move the logic of onNewFrame to the controller. Then the user whenever wants to export will simply create a Exporter with the frames as parameter in the constructor. This way will simplify testing in the future as well. @ueman

I don't think that's the way to go. I'm currently experimenting with a sticky background isolate, which does the processing right at the time of the arrival of new frames. That makes exporting a gif way faster.

But apart from that I agree. It would make everything easier, but it would also limit you in other ways. Maybe the `controller.export` should just return the `exporter`. Then you could also write an exporter, which nests multiple other `exporters` which then enables exporting to various formats

**Comment by omartinma** [comment]
> > Another approach to avoid the dependency between Exporter and ScreenRecorderController might be move the logic of onNewFrame to the controller. Then the user whenever wants to export will simply create a Exporter with the frames as parameter in the constructor. This way will simplify testing in the future as well. @ueman
> 
> I don't think that's the way to go. I'm currently experimenting with a sticky background isolate, which does the processing right at the time of the arrival of new frames. That makes exporting a gif way faster.
> 
> But apart from that I agree. It would make everything easier, but it would also limit you in other ways. Maybe the `controller.export` should just return the `exporter`. Then you could also write an exporter, which nests multiple other `exporters` which then enables exporting to various formats

Then I have the feeling that there is too much purpose on the package IMO. For me I see 2 clear paths here:

- Record screen.
- Generates GIF.

If they continue coupled with each other I think will prevent the people who dont want to generate the GIF at all to fully use the package.

**Comment by omartinma** [comment]
Anyway what are your thoughts about the changes on the current API?

**Comment by ueman** [comment]
> Anyway what are your thoughts about the changes on the current API?

I'm still not 100% convinced, but I'm not using it myself, and you're using it, so I'll trust you on this. Let's move on with this and iterate if it doesn't work out. Can you raise the version to 0.2.0 and add a changelog entry?

**Review by ueman — APPROVED** [review]
> Changelog updated :D Thanks a lot again!

You're welcome.

> if you prefer we can jump on a call to discuss the API or any other future improvement

I'll come back to you. Right now, I'm kinda busy

> I was planning to include support as well for JS workers since the current approach of computing is not working there

I would love to see support for JS workers.

**Pull request merged**
